project_id = "zdngnqkjjxzfnnxcolyz"

[functions.analyze-dream]
verify_jwt = false

[functions.analyze-dream-patterns]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-data-sync]
verify_jwt = true

[functions.admin-credit-fix]
verify_jwt = true

[functions.sync-stripe-subscription]
verify_jwt = true